language: node_js
node_js:
- '0.10'
addons:
    sauce_connect: true
before_script:
- export DISPLAY=:99.0
- export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g bower
- bower install --config.interactive=0
- gulp --version
- bower --version
env:
  global:
  - secure: iKE9Qp+6ZKCr1Xon087MKA267kgIItF/RMuEDUCwNzsD3VvZHdzqi00qml3iyZ5zHEWTWEev0gBQdVDNQbyzTM/6Eu60TXQcx6Veqgm6jkTmOC9gtiY1AA/SEm6eEm2dZKVKagQpaLiK3GxVPSeeGygGqDMPpOUKNnHdT4jZHDQ=
  - secure: Snq1vfb80lHE4pkhqVfAt6a2mwO/mMA4hkQcVdP034AxrzuD82xuaZgsFOt+jidXdcZwXcZeJTOG8uoQnU8Sq/WTvx/OGhOhaYR6B2qNT3D9k/dOl3gc/7+ZmxZ9bGq++pXTPIwKinhJ0wNrBWCmwNBuohZDE95aAPItVmGJP6c=
